version: "3"
services:
  heimdall:
    image: linuxserver/heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - heimdall-data:/config
    labels:
      - "traefik.http.routers.heimdall.rule=Host(`gluteus.owodunni.home`)"

volumes:
  heimdall-data: